version: "3"

services:
  lava:
    image: ghcr.io/nat1anwastaken/lava:latest
    build: .
    restart: always
    env_file:
      - stack.env
    volumes:
      - "./configs:/lava/configs"
